# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-testnet-sepolia        # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#     - chain-name: ethereum-mainnet                # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet-base-1
      url: https://mainnet.base.org

# ==========================================================================
production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: ethereum-mainnet-base-1
      url: https://mainnet.base.org
    - chain-name: ethereum-mainnet
      url: https://mainnet.gateway.tenderly.co

# ==========================================================================
polygon-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: polygon-mainnet
      url: ${RPC_URL_POLYGON}

# ==========================================================================
avalanche-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: avalanche-mainnet
      url: ${RPC_URL_AVALANCHE}

# ==========================================================================
arbitrum-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: ${RPC_URL_ARBITRUM}

# ==========================================================================
optimism-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: ethereum-mainnet-optimism-1
      url: ${RPC_URL_OPTIMISM}

# ==========================================================================
base-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: ethereum-mainnet-base-1
      url: ${RPC_URL_BASE}

# ==========================================================================
bnb-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: binance_smart_chain-mainnet
      url: ${RPC_URL_BNB}

# ==========================================================================
ethereum-production-settings:
  account:
      workflow-owner-address: "0x73494691C9B28b91A0b4C9dF213c1893fddA3a3B"
      workflow-name: "deployer"
  rpcs:
    - chain-name: ethereum-mainnet
      url: ${RPC_URL_ETHEREUM}
