export const governanceAbi = [
  {
    name: 'getProposal',
    type: 'function',
    stateMutability: 'view',
    inputs: [{name: 'proposalId', type: 'uint256'}],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {name: 'state', type: 'uint8'},
          {name: 'accessLevel', type: 'uint8'},
          {name: 'creationTime', type: 'uint40'},
          {name: 'votingDuration', type: 'uint24'},
          {name: 'votingActivationTime', type: 'uint40'},
          {name: 'queuingTime', type: 'uint40'},
          {name: 'cancelTimestamp', type: 'uint40'},
          {name: 'creator', type: 'address'},
          {name: 'votingPortal', type: 'address'},
          {name: 'snapshotBlockHash', type: 'bytes32'},
          {name: 'ipfsHash', type: 'bytes32'},
          {name: 'forVotes', type: 'uint128'},
          {name: 'againstVotes', type: 'uint128'},
          {name: 'cancellationFee', type: 'uint256'},
          {
            name: 'payloads',
            type: 'tuple[]',
            components: [
              {name: 'chain', type: 'uint256'},
              {name: 'accessLevel', type: 'uint8'},
              {name: 'payloadsController', type: 'address'},
              {name: 'payloadId', type: 'uint40'},
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'getProposalsCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
  },
  {
    name: 'getVotingConfig',
    type: 'function',
    stateMutability: 'view',
    inputs: [{name: 'accessLevel', type: 'uint8'}],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {name: 'coolDownBeforeVotingStart', type: 'uint24'},
          {name: 'votingDuration', type: 'uint24'},
          {name: 'yesThreshold', type: 'uint56'},
          {name: 'yesNoDifferential', type: 'uint56'},
          {name: 'minPropositionPower', type: 'uint56'},
        ],
      },
    ],
  },
  {
    name: 'getPowerStrategy',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{name: '', type: 'address'}],
  },
  {
    name: 'COOLDOWN_PERIOD',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
  },
  {
    name: 'PRECISION_DIVIDER',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
  },
  {
    name: 'activateVoting',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{name: 'proposalId', type: 'uint256'}],
    outputs: [],
  },
  {
    name: 'executeProposal',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{name: 'proposalId', type: 'uint256'}],
    outputs: [],
  },
  {
    name: 'cancelProposal',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{name: 'proposalId', type: 'uint256'}],
    outputs: [],
  },
  {
    name: 'redeemCancellationFee',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{name: 'proposalIds', type: 'uint256[]'}],
    outputs: [],
  },
  {
    // Live proposal state (computes Failed/Expired dynamically from timestamps —
    // unlike the stored state in `getProposal`).
    name: 'getProposalState',
    type: 'function',
    stateMutability: 'view',
    inputs: [{name: 'proposalId', type: 'uint256'}],
    outputs: [{name: '', type: 'uint8'}],
  },
  {
    name: 'getCancellationFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
  },
  {
    name: 'VotingActivated',
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'proposalId', type: 'uint256', indexed: true},
      {name: 'snapshotBlockHash', type: 'bytes32', indexed: true},
      {name: 'votingDuration', type: 'uint24', indexed: false},
    ],
  },
] as const;
